### PR TITLE
Updated dependencies for newer rails versions

### PR DESCRIPTION
**Pull request by costaraphael**
I updated the dependencies on the .gemspec file so it can match other rails versions. I needed this because my application is rocking Rails 4.2 for now this gem requires Rails 4.0 or 4.1, depending on the version.

### CODE REVIEW

**Comment by sindrenm** [comment]
Hi, @vidalraphael! Thanks for your PR. However, instead of allowing any Rails version above 4.0.0, maybe we want to allow any minor and patch version between 4.0.0 and 5.0.0, like this:

``` ruby
s.add_dependency "rails", "~> 4.0"
```

That way, we don't get any nasty surprises when 5.0.0 gets released, hoping the Rails team uses semantic versioning to the best of their abilities. :smiley:

**Comment by costaraphael** [comment]
Updated the Rails dependency according to the one mentioned on the other PR.

**Comment by timkurvers** [comment]
Hi @vidalraphael, looks great!

I normalized the codebase a bit, could you rebase or merge with master?

**Comment by timkurvers** [comment]
Feel free to also update the README to document supported Rails versions.

**Pull request closed without merging**
